/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package supplier.infrastructure;

import exceptions.ValidationModelException;
import java.sql.SQLException;
import models.Proveedor;
import repositories.ProveedorRepository;
import views.MessageHandler;
import views.RealTimeValidator;
import views.ValidationRule;

/**
 *
 * @author ili
 */
@SuppressWarnings("serial")
public class CrearProveedorModal extends javax.swing.JDialog {

    private final ProveedorRepository proveedorRepository;
    private final ProveedorFrame parent;

    public CrearProveedorModal(java.awt.Frame parent, ProveedorRepository proveedorRepository) {
        super(parent, true);
        initComponents();
        this.parent = (ProveedorFrame) parent;
        this.proveedorRepository = proveedorRepository;

        RealTimeValidator.addValidation(nombre, new ValidationRule(Proveedor::NombreValido, nombreError));
        RealTimeValidator.addValidation(direccion, new ValidationRule(Proveedor::DireccionValida, direccionError));
        RealTimeValidator.addValidation(telefono, new ValidationRule(Proveedor::TelefonoValido, telefonoError));
        RealTimeValidator.addValidation(email, new ValidationRule(Proveedor::EmailValido, emailError));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        proveedorlbl1 = new javax.swing.JLabel();
        telefonoError = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        emailError = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        direccionError = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        nombrePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreError = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        tituloLbl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        cancelarBtn1 = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar proveedor");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proveedorlbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        proveedorlbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proveedorlbl1.setText("Teléfono");
        proveedorlbl1.setPreferredSize(new java.awt.Dimension(250, 16));
        jPanel5.add(proveedorlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        telefonoError.setBackground(new java.awt.Color(254, 254, 254));
        telefonoError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        telefonoError.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        telefonoError.setOpaque(true);
        jPanel5.add(telefonoError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 400, 20));

        telefono.setToolTipText("");
        telefono.setActionCommand("<Not Set>");
        telefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        telefono.setMargin(new java.awt.Insets(2, 10, 2, 6));
        telefono.setOpaque(true);
        jPanel5.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 400, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 385, 700, 70));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Email");
        jLabel9.setPreferredSize(new java.awt.Dimension(250, 16));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        emailError.setBackground(new java.awt.Color(254, 254, 254));
        emailError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        emailError.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        emailError.setOpaque(true);
        jPanel1.add(emailError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 400, 20));

        email.setToolTipText("");
        email.setActionCommand("<Not Set>");
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        email.setMargin(new java.awt.Insets(2, 10, 2, 6));
        email.setOpaque(true);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 400, 40));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, 700, -1));

        jPanel.setBackground(new java.awt.Color(254, 254, 254));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dirección ");
        jLabel8.setPreferredSize(new java.awt.Dimension(250, 16));
        jPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        direccionError.setBackground(new java.awt.Color(254, 254, 254));
        direccionError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        direccionError.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        direccionError.setOpaque(true);
        jPanel.add(direccionError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 400, 20));

        direccion.setToolTipText("");
        direccion.setActionCommand("<Not Set>");
        direccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        direccion.setMargin(new java.awt.Insets(2, 10, 2, 6));
        direccion.setOpaque(true);
        jPanel.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 400, 40));

        jPanel2.add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 202, 700, -1));

        nombrePanel.setBackground(new java.awt.Color(254, 254, 254));
        nombrePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 16));
        nombrePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        nombreError.setBackground(new java.awt.Color(254, 254, 254));
        nombreError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        nombreError.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        nombreError.setOpaque(true);
        nombrePanel.add(nombreError, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 400, 20));

        nombre.setToolTipText("");
        nombre.setActionCommand("<Not Set>");
        nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        nombre.setMargin(new java.awt.Insets(2, 10, 2, 6));
        nombre.setOpaque(true);
        nombrePanel.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 400, 40));

        jPanel2.add(nombrePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, 700, -1));

        tituloLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("Agregar proveedor");
        jPanel2.add(tituloLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 700, 40));

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarBtn1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        cancelarBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBtn1.setText("Cancelar");
        cancelarBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtn1ActionPerformed(evt);
            }
        });
        jPanel6.add(cancelarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 120, 30));

        agregarBtn.setBackground(new java.awt.Color(129, 140, 248));
        agregarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregarBtn.setForeground(new java.awt.Color(255, 255, 255));
        agregarBtn.setText("Agregar");
        agregarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        jPanel6.add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 140, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 700, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 580));

        setSize(new java.awt.Dimension(716, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        Proveedor proveedor = new Proveedor();

        try {
            proveedor.setNombre(nombre.getText());
            proveedor.setDireccion(direccion.getText());
            proveedor.setEmail(email.getText());
            proveedor.setTelefono(telefono.getText());
            proveedorRepository.save(proveedor);

            dispose();
            parent.loadEntries();
            MessageHandler.showSuccessMessage("Proveedor agregado correctamente", null);
        } catch (SQLException | ValidationModelException ex) {
            MessageHandler.showErrorMessage(ex.getMessage());
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void cancelarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtn1ActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton cancelarBtn1;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionError;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailError;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreError;
    private javax.swing.JPanel nombrePanel;
    private javax.swing.JLabel proveedorlbl1;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoError;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
