/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.proveedor;

import exceptions.ValidationModelException;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.ProveedorCriteria;
import repositories.ProveedorRepository;
import views.MessageHandler;
import views.tabla.TableActionCellEditor;
import views.tabla.TableActionCellRender;
import views.tabla.TableActionEvent;

/**
 *
 * @author ili
 */
@SuppressWarnings("serial")
public final class ProveedorFrame extends javax.swing.JFrame {

    private final ProveedorRepository proveedorRepository;
    private final DefaultTableModel model;
    private final FilterProveedorModal filterProveedorModal;
    private ProveedorCriteria criteria;

    public ProveedorFrame() {
        initComponents();
        setSize(1300, 720);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Proveedores");

        this.proveedorRepository = new ProveedorRepository();
        this.criteria = new ProveedorCriteria();
        this.filterProveedorModal = new FilterProveedorModal(ProveedorFrame.this, criteria);

        model = (DefaultTableModel) table.getModel();
        loadEntries(showDeleted.isSelected());

        TableActionEvent actionEvent = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                long id = (long) model.getValueAt(row, 0);
                new EditarProveedorModal(ProveedorFrame.this, proveedorRepository, id, showDeleted.isSelected()).setVisible(true);
            }

            @Override
            public void onDelete(int row) {
                if (table.isEditing()) {
                    table.getCellEditor().stopCellEditing();
                }

                long id = (long) model.getValueAt(row, 0);
                int option = JOptionPane.showConfirmDialog(ProveedorFrame.this,
                        "¿Estás seguro de que desea eliminar el proveedor con ID '" + id + "' ?", "Eliminar permanentemente",
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (option == JOptionPane.YES_OPTION) {
                    try {
                        proveedorRepository.delete(id);
                        loadEntries(showDeleted.isSelected());
                        MessageHandler.showSuccessMessage("Eliminado correctamente");
                    } catch (SQLException ex) {
                        MessageHandler.showErrorMessage(ex.getMessage());
                    }
                }
            }

            @Override
            public void onShow(int row) {
                long id = (long) model.getValueAt(row, 0);
                try {
                    new VerProveedorModal(ProveedorFrame.this, proveedorRepository.findById(id), proveedorRepository).setVisible(true);
                } catch (SQLException | ValidationModelException ex) {
                    MessageHandler.showErrorMessage(ex.getMessage());
                }
            }
        };

        table.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
        table.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(actionEvent));

        showDeleted.addItemListener((ItemEvent e) -> {
            loadEntries(e.getStateChange() == ItemEvent.SELECTED);

        });
        quitarFiltrosBtn.setVisible(false);

    }

    public void setCriteria(ProveedorCriteria pc) {
        this.criteria = pc;
        loadEntries(showDeleted.isSelected());
        filterByLbl.setText("Filtro aplicados");
        quitarFiltrosBtn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        filterBtn = new javax.swing.JButton();
        crearBtn = new javax.swing.JButton();
        showDeleted = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        filterByLbl = new javax.swing.JLabel();
        quitarFiltrosBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("PROVEEDORES ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, 53));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre ", "Direccion", "Email ", "Telefono", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(50);
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(10);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(200);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 1218, 581));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        filterBtn.setBackground(new java.awt.Color(56, 189, 248));
        filterBtn.setFont(new java.awt.Font("Nimbus Sans", 1, 14)); // NOI18N
        filterBtn.setForeground(new java.awt.Color(255, 255, 255));
        filterBtn.setText("Filtrar");
        filterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(filterBtn, gridBagConstraints);

        crearBtn.setBackground(new java.awt.Color(129, 140, 248));
        crearBtn.setFont(new java.awt.Font("Noto Sans Myanmar", 1, 14)); // NOI18N
        crearBtn.setForeground(new java.awt.Color(255, 255, 255));
        crearBtn.setText("Agregar proveedor");
        crearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        jPanel2.add(crearBtn, gridBagConstraints);

        showDeleted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showDeleted.setText("Mostrar eliminados");
        showDeleted.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(showDeleted, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 530, 50));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        filterByLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        filterByLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filterByLbl.setText("Filtros aplicados");
        jPanel1.add(filterByLbl);

        quitarFiltrosBtn.setBackground(new java.awt.Color(251, 113, 133));
        quitarFiltrosBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quitarFiltrosBtn.setForeground(new java.awt.Color(255, 255, 255));
        quitarFiltrosBtn.setText("Quitar filtros");
        quitarFiltrosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitarFiltrosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarFiltrosBtnActionPerformed(evt);
            }
        });
        jPanel1.add(quitarFiltrosBtn);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 340, 40));

        setSize(new java.awt.Dimension(1300, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBtnActionPerformed
        new CrearProveedorModal(ProveedorFrame.this, proveedorRepository, showDeleted.isSelected()).setVisible(true);

    }//GEN-LAST:event_crearBtnActionPerformed

    private void quitarFiltrosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarFiltrosBtnActionPerformed
        this.criteria = new ProveedorCriteria();
        filterProveedorModal.setCriteria(criteria);
        loadEntries(showDeleted.isSelected());
        quitarFiltrosBtn.setVisible(false);
        filterByLbl.setText("");
    }//GEN-LAST:event_quitarFiltrosBtnActionPerformed

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        filterProveedorModal.setVisible(true);
    }//GEN-LAST:event_filterBtnActionPerformed

    public void loadEntries(boolean showDelete) {
        model.setRowCount(0);
        try {
            proveedorRepository.findAll(showDelete, criteria).forEach(proveedor -> {
                Object[] row = new Object[6];
                row[0] = proveedor.getId();
                row[1] = proveedor.getNombre();
                row[2] = proveedor.getDireccion();
                row[3] = proveedor.getEmail();
                row[4] = proveedor.getTelefono();
                row[5] = "";
                model.addRow(row);
            });
        } catch (SQLException | ValidationModelException ex) {
            MessageHandler.showErrorMessage(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearBtn;
    private javax.swing.JButton filterBtn;
    private javax.swing.JLabel filterByLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton quitarFiltrosBtn;
    private javax.swing.JCheckBox showDeleted;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
