DROP SCHEMA IF EXISTS tiendita;
CREATE SCHEMA tiendita;
USE tiendita;

CREATE TABLE proveedores (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  direccion VARCHAR(255) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  email VARCHAR(40) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1
); 

CREATE TABLE productos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(500) NOT NULL,
  codigo_barras VARCHAR(13) NOT NULL UNIQUE,
  precio_publico DECIMAL(10,2) NOT NULL,
  costo DECIMAL(10,2) NOT NULL,
  id_proveedor INT UNSIGNED,
  categoria VARCHAR(50) NOT NULL,
  marca VARCHAR(255) NOT NULL, 
  FOREIGN KEY (id_proveedor) REFERENCES proveedores(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE inventario (
  id_producto INT UNSIGNED NOT NULL PRIMARY KEY,
  stock INT UNSIGNED NOT NULL,
  FOREIGN KEY (id_producto) REFERENCES productos(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE usuarios (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  nombre VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  rol ENUM('administrador', 'cajero') NOT NULL
);

CREATE TABLE ventas (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fecha TIMESTAMP NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  usuario_id INT UNSIGNED,
  forma_pago VARCHAR(50),
  FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE detalles_venta (
  id_venta INT UNSIGNED NOT NULL,
  id_producto INT UNSIGNED NOT NULL,
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (id_venta) REFERENCES ventas(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_producto) REFERENCES productos(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE compras (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fecha TIMESTAMP NOT NULL,
  id_proveedor INT UNSIGNED NOT NULL,
  forma_pago VARCHAR(50),
  total DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (id_proveedor) REFERENCES proveedores(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE detalles_compra (
  id_compra INT UNSIGNED NOT NULL,
  id_producto INT UNSIGNED NOT NULL,
  cantidad INT NOT NULL,
  precio_coste DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (id_compra) REFERENCES compras(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (id_producto) REFERENCES productos(id) ON DELETE RESTRICT ON UPDATE CASCADE
);