package views.inventario;

import exceptions.ValidationModelException;
import java.sql.SQLException;
import models.Producto;
import repositories.InventarioRepository;
import repositories.ProductoRepository;
import repositories.ProveedorRepository;
import views.MessageHandler;

/**
 *
 * @author Carlos
 */
@SuppressWarnings("serial")
public class VerProductoModal extends javax.swing.JDialog {

    public VerProductoModal(java.awt.Frame parent, Producto producto, ProductoRepository productoRepository, ProveedorRepository proveedorRepository) {
        super(parent, true);
        initComponents();
        setTitle("Información de producto");
        InventarioRepository in = new InventarioRepository();

        id.setText(String.valueOf(producto.getId()));
        nombre.setText(producto.getNombre());
        codigoBarras.setText(producto.getCodigoBarras());
        precio.setText(String.valueOf(producto.getPrecioPublico()));
        costo.setText(String.valueOf(producto.getCosto()));
        categoria.setText(producto.getCategoria());

        try {
            proveedor.setText(proveedorRepository.findById(producto.getIdProveedor()).getNombre());
            stock.setText(String.valueOf(in.getProductStock(producto.getId())));
        } catch (SQLException | ValidationModelException ex) {
            MessageHandler.showErrorMessage(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        proveedor = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoBarras = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        costo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(990, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 430, 26));

        jLabel4.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(129, 140, 248));
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 56, 26));

        jLabel5.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(129, 140, 248));
        jLabel5.setText("Precio $");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 100, 31));

        jLabel6.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(129, 140, 248));
        jLabel6.setText("Proveedor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 91, 26));

        jLabel7.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(129, 140, 248));
        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 81, 26));

        id.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 270, 26));

        precio.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 280, 26));

        proveedor.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 410, 26));

        categoria.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 320, 26));

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(129, 140, 248));
        jLabel3.setText("Categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 150, 26));

        codigoBarras.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(codigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 320, 26));

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(129, 140, 248));
        jLabel8.setText("Codigo de barras");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 170, 26));

        costo.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 320, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalles del producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 50));

        jLabel12.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(129, 140, 248));
        jLabel12.setText("Costo               $");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 220, 31));

        stock.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 320, 30));

        jLabel14.setFont(new java.awt.Font("Liberation Mono", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(129, 140, 248));
        jLabel14.setText("Cantidad");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 150, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 500));

        setSize(new java.awt.Dimension(1316, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel codigoBarras;
    private javax.swing.JLabel costo;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel proveedor;
    private javax.swing.JLabel stock;
    // End of variables declaration//GEN-END:variables
}
